apiVersion: core.kubefunction.io/v1alpha1
kind: FunctionEvent
metadata:
  labels:
    app.kubernetes.io/name: functionevent
    app.kubernetes.io/instance: functionevent-sample
    app.kubernetes.io/part-of: kubefunction
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: kubefunction
  name: functionevent-sample
spec:
  functionName: wasmrun-function
  replicas: 1
  command:
    - "greet"
  args:
    - "KubeFunction"
